defaults: &defaults
  api_host: https://api.opensuse.org
  api_username: test
  api_password: test
  relative_url_root:
development:
  <<: *defaults
  api_username: wiki_hermes
  api_password: w_h_p1
test:
  <<: *defaults
  api_username: wiki_hermes
  api_password: w_h_p1
production:
  <<: *defaults
  relative_url_root:
  api_username: <%= ENV['API_USERNAME'] %>
  api_password: <%= ENV['API_PASSWORD'] %>
  use_static: software.o.o
  opensuse_cookie: <%= ENV['OPENSUSE_COOKIE'] %>
